glpmr_virtual_machine:
    resource: "@GlpmrVirtualMachineBundle/Resources/config/routing.yml"
    prefix:   /Machine

glpmr_peripherique:
    resource: "@GlpmrPeripheriqueBundle/Resources/config/routing.yml"
    prefix:   /Peripherique

glpmr_authentification:
    resource: "@GlpmrAuthentificationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
