# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #connection_DB:
    #class: Glpmr\PeripheriqueBundle\Entity\PeripheriqueDAO;
    #arguments: [@doctrine.dbal.%connection_DB%_connection]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
