glpmr_peripherique_gestion:
    path:     /
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:lister }
    
glpmr_peripherique_ajouter:
    path:   /ajouter
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:ajouter }
    
glpmr_peripherique_modifier:
    path:   /modifier
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:modifier }
    
glpmr_peripherique_supprimer:
    path:   /supprimer
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:supprimer }

glpmr_admin_recherche:
    path:   /recherche
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:recherche }

glpmr_admin_resultat_recherche:
    path:   /resultat
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:resultat }

glpmr_admin_supprimer_groupe:
    path:     /supprimerGroupe
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:supprimerGroupe }

glpmr_admin_supprimer_groupe_valider:
    path:     /supprimerGroupeValider
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:supprimerGroupeValider }

glpmr_test:
    path: /test
    defaults: { _controller: GlpmrPeripheriqueBundle:Peripherique:test }